CREATE TABLE TBL_CAR (
	CAR_NUMBER NUMBER, -- 차량번호
	CAR_BRAND VARCHAR2(500), -- 브랜드명
	CAR_DATE DATE, -- 출시일
	CAR_COLOR VARCHAR2(100), -- 색상
	CAR_PRICE NUMBER -- 가격
);

-- 여기서 PK가 될 수 있는 조건의 칼럼은 차량번호이다. 
ALTER TABLE TBL_CAR
	ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_NUMBER);

-- 제약조건 삭제
ALTER TABLE TBL_CAR
	DROP CONSTRAINT PK_CAR;

DROP TABLE TBL_CAR;

--테이블 생성과 동시에 제약조건 설정
CREATE TABLE TBL_CAR (
	CAR_NUMBER NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_BRAND VARCHAR2(500),
	CAR_DATE DATE,
	CAR_COLOR VARCHAR2(100),
	CAR_PRICE NUMBER
);

SELECT * FROM TBL_CAR;

-----
CREATE TABLE TBL_ANIMAL(
	ANIMAL_NUMBER NUMBER,
	ANIMAL_KIND VARCHAR2(500),
	ANIMAL_AGE NUMBER
);

SELECT * FROM TBL_ANIMAL;

-- 제약 조건 추가
ALTER TABLE TBL_ANIMAL
ADD CONSTRAINT PK_ANIMAL PRIMARY KEY (ANIMAL_NUMBER);

-- 제약 조건 삭제
ALTER TABLE TBL_ANIMAL
DROP CONSTRAINT PK_ANIMAL;


--------
CREATE TABLE TBL_EX1(
	EX1_NUMBER NUMBER CONSTRAINT PK_EX1 PRIMARY KEY,
	EX1_NAME VARCHAR2(500),
	EX1_PRICE NUMBER
);

INSERT INTO TBL_EX1
VALUES (1,'아이패드', 790000)

-- PK 중복이라 오류남
INSERT INTO TBL_EX1 
VALUES (1,'갤럭시워치', 300000);

INSERT INTO TBL_EX1 
VALUES (2,'갤럭시워치', 300000);

-- PK NULL 불가
INSERT INTO TBL_EX1 
VALUES (NULL,'LG그램', 1000000);

INSERT INTO TBL_EX1 
VALUES (3,'LG그램', 1000000);

SELECT * FROM TBL_EX1;


-- FK 관계로 설정
CREATE TABLE TBL_SCHOOL(
	SCHOOL_NUMBER NUMBER CONSTRAINT PK_SCHOOL PRIMARY KEY,
	SCHOOL_NAME VARCHAR2(500)
);

CREATE TABLE TBL_SCL_STUDENT(
	SCL_STUDENT_NUMBER NUMBER CONSTRAINT PK_SCL_STUDENT PRIMARY KEY,
	SCL_STUDENT_NAME VARCHAR2(500),
	SCL_STUDENT_AGE NUMBER,
	SCHOOL_NUMBER NUMBER,
	CONSTRAINT FK_SCHOOL FOREIGN KEY(SCHOOL_NUMBER) -- TBL_SCL_STUDENT
	REFERENCES TBL_SCHOOL(SCHOOL_NUMBER)
);

INSERT INTO TBL_SCHOOL
VALUES(3,'PYTHON 고등학교');

INSERT INTO TBL_SCL_STUDENT
VALUES(1,'김철수', 17, 4); -- 오류발생: SCHOOL_NUMBER(부모테이블)에 없는 값을 저장하려했다.  

INSERT INTO TBL_SCL_STUDENT
VALUES(3,'이유리', 18, NULL);

INSERT INTO TBL_SCL_STUDENT
VALUES(4,'김영희', 19, 2);

UPDATE TBL_SCL_STUDENT 
SET SCHOOL_NUMBER = 2
WHERE SCHOOL_NUMBER IS NULL;

SELECT * FROM TBL_SCHOOL;
SELECT * FROM TBL_SCL_STUDENT;



CREATE TABLE TBL_EX2_STUDENT(
	EX2_STUDENT_NUMBER NUMBER CONSTRAINT PK_EX2_STUDENT PRIMARY KEY, -- PK설정
	EX2_STUDENT_ID VARCHAR2(500) UNIQUE,
	EX2_STUDENT_NAME VARCHAR2(500) NOT NULL,
	EX2_STUDENT_MAJOR VARCHAR2(500),
	EX2_STUDENT_GENDER CHAR(1)
	DEFAULT 'M' CHECK(EX2_STUDENT_GENDER ='M' OR EX2_STUDENT_GENDER = 'F')
);



