-- [과제]
-- 1. TBL_TEAM 테이블 생성
CREATE TABLE TBL_TEAM (
	TEAM_NUMBER NUMBER CONSTRAINT PK_TEAM PRIMARY KEY,
	TEAM_NAME VARCHAR2(500) UNIQUE,
	TEAM_ADDRESS VARCHAR2(500) DEFAULT '미정'
);

SELECT * FROM TBL_TEAM;


-- 2. TBL_PLAYER 테이블 생성
CREATE TABLE TBL_PLAYER(
	PLAYER_NUMBER NUMBER CONSTRAINT PK_PLAYER PRIMARY KEY,
	PLAYER_NAME VARCHAR2(500),
	PLAYER_AGE NUMBER,
	PLAYER_PHONE_NUMBER NUMBER UNIQUE,
	PLAYER_GENDER VARCHAR2(1) CHECK(PLAYER_GENDER = 'M' OR PLAYER_GENDER ='W'),
	TEAM_NUMBER NUMBER,
	CONSTRAINT FK_TEAM FOREIGN KEY(TEAM_NUMBER) REFERENCE TBL_TEAM(TEAM_NUMBER)
);

SELECT * FROM
-- 3. 완성된 TBL_TEAM 테이블에 아래 값 삽입
-- (1,'FC서울')
-- (2,'수원 삼성','수원')
-- (3, '전북 현대', '전북')

-- 4. 완성된 TBL_PLAYER 테이블에
-- 아래 값 삽입
-- (1,'홍길동',20,'010-1111-1111','M',1)
-- (2,'김철수',21,'010-2222-2222','M',1)
-- (3, '김유리',22, '010-3333-3333','W',2)
-- (4,'이훈이',23,'010-5555-5555', 'M',3)
-- (5,'김맹구',24, '010-6666-6666', 'M',2)









   

   






   