CREATE TABLE TBL_MEMBER(
	MEMBER_ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(500),
	MEMBER_AGE NUMBER,
	MEMBER_PHONE VARCHAR2(500) UNIQUE,
	MEMBER_ADDRESS VARCHAR2(500)
);

SELECT * FROM TBL_MEMBER;


CREATE TABLE TBL_BOOK(
	BOOK_NUMBER NUMBER CONSTRAINT PK_BOOK PRIMARY KEY,
	BOOK_NAME VARCHAR2(500),
	BOOK_CATEGORY VARCHAR2(500) 
		CHECK(
			BOOK_CATEGORY IN('인문학', '추리', 'IT', '로맨스')
		),
	MEMBER_ID NUMBER,
	CONSTRAINT FK_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(MEMBER_ID)
);

SELECT * FROM TBL_BOOK; 




