-- 시퀀스 사용
-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOOK;
CREATE SEQUENCE SEQ_MEMBER;

-- 시퀀스 사용
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_BOOK;

DELETE FROM TBL_BOOK;
DELETE FROM TBL_MEMBER;

CREATE TABLE TBL_MEMBER(
   MEMBER_NUMBER NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_NAME VARCHAR2(500),
   MEMBER_AGE NUMBER,
   MEMBER_PHONE_NUMBER VARCHAR2(500) UNIQUE,
   MEMBER_ADDRESS VARCHAR2(500)
);

CREATE TABLE TBL_BOOK(
   BOOK_NUMBER NUMBER CONSTRAINT PK_BOOK PRIMARY KEY,
   BOOK_NAME VARCHAR2(500),
   BOOK_CATEGORY VARCHAR2(500) CHECK(
      BOOK_CATEGORY IN('인문학','추리','IT','로맨스') 
   ),
   MEMBER_NUMBER NUMBER,
   CONSTRAINT FK_MEMBER FOREIGN KEY(MEMBER_NUMBER) REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

-- 시퀀스는 테이블에 값을 넣어줄때 사용된다.
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL , '홍길동', 22, '010-1111-1111','서울시');

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL , '신짱구', 25, '010-2222-2222', '서울시');

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL , '김철수', 30, '010-3333-3333', '경기도');

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_BOOK
VALUES(SEQ_BOOK.NEXTVAL , '셜록', '추리', NULL);

INSERT INTO TBL_BOOK
VALUES(SEQ_BOOK.NEXTVAL, 'DBMS 완정 정복', 'IT', NULL);

INSERT INTO TBL_BOOK
VALUES(SEQ_BOOK.NEXTVAL , 'PYTHON 완전 정복', 'IT', NULL);

SELECT * FROM TBL_BOOK;
SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_BOOK
VALUES(SEQ_MEMBER.NEXTVAL , 'C언어 완전 정복', 'IT', NULL);

INSERT INTO TBL_BOOK
VALUES(SEQ_BOOK.NEXTVAL , '오이대왕' , '인문학', NULL);

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL , '이유리' , 28 , '010-7777-7777', '경기도');

SELECT * FROM TBL_MEMBER;

-- 시퀀스 삭제 : 1부터 증가되는 값을 만들어내는 기능을 삭제
DROP SEQUENCE SEQ_BOOK;
DROP SEQUENCE SEQ_MEMBER;

-- 테이블 생성
CREATE TABLE TBL_TEST(
   TEST_NUMBER NUMBER CONSTRAINT PK_TEST PRIMARY KEY
);

-- 시퀀스 시작값 100으로 설정
CREATE SEQUENCE SEQ_TEST START WITH 100;

INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL);

SELECT * FROM TBL_TEST;
DROP SEQUENCE SEQ_TEST;

-- 시퀀스 숫자 5씩 증가
CREATE SEQUENCE SEQ_TEST INCREMENT BY 5;

INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL);

SELECT * FROM TBL_TEST;

DROP SEQUENCE SEQ_TEST;

-- 옵션 동시 설정
DELETE FROM TBL_TEST;

CREATE SEQUENCE SEQ_TEST START WITH 200 INCREMENT BY 3;

INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL);

SELECT * FROM TBL_TEST;
